#From almalinux:9
#RUN dnf install nginx -y        # inastlls nginx inside the alma linux

FROM run:v1  # if run:vi image already present in local docker repo i server we can direct use them (layering?)
CMD ["nginx", "-g", "daemon odd;"]